all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
batch_size: 16
c_alpha_max_neighbors: 24
cache_path: data/cache
config: null
cross_distance_embed_dim: 64
cross_max_distance: 80
cudnn_benchmark: true
data_dir: data/PDBBind_processed/
distance_embed_dim: 64
dropout: 0.1
dynamic_max_cross: false
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: data/esm2_3billion_embeddings.pt
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
limit_complexes: 0
log_dir: workdir
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
n_epochs: 100
no_batch_norm: false
no_torsion: false
ns: 48
num_conformers: 1
num_conv_layers: 3
num_dataloader_workers: 1
num_inference_complexes: 500
num_workers: 1
nv: 6
pin_memory: false
project: difdock_train
receptor_radius: 15.0
remove_hs: true
restart_dir: null
restart_lr: null
rot_sigma_max: 1.65
rot_sigma_min: 0.1
rot_weight: 0.33
run_name: rank_l3
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sigma_embed_dim: 64
split_test: data/splits/timesplit_test
split_train: data/splits/timesplit_no_lig_overlap_train
split_val: data/splits/timesplit_no_lig_overlap_val
test_sigma_intervals: false
tor_sigma_max: 3.14
tor_sigma_min: 0.0314
tor_weight: 0.33
tr_sigma_max: 30
tr_sigma_min: 0.1
tr_weight: 0.33
train_inference_freq: null
use_ema: true
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: false
